### PR TITLE
Improved performance of SceneRendererES2 on Drawables that have local Matrix

### PR DESCRIPTION
**Pull request by RootDmytro**
reusing precalculated matrixes to avoid their heavy recalculation on every iteration (for each drawable)

### CODE REVIEW

**Comment by saildronesteve** [comment]
Neat!  Are you doing something where this shows up as a big item?

**Comment by RootDmytro** [comment]
I determined it to be the biggest manifested performance bottleneck, that created noticeable lag in case of our app, so I just alleviated it.
I don't know why all our markers have their own `mat` but this part of code can benefit from simplification and it solves the performance problem.

**Comment by mousebird** [comment]
Thinking about this further, if this is models, then you might look at using addModelInstances:
The implementation should be a bit more efficient than single models.

**Comment by RootDmytro** [comment]
> ... if this is models ...
I use just Screen Markers

> You must be using a lot of models, I presume?
I encountered drop in performance at about 300-600 drawables being processed in that method

**Comment by mousebird** [comment]
That's an enormous number of drawables for screen markers.

How are you adding your textures?  Have you tried adding them to a texture atlas?

**Pull request merged**
