### PR TITLE
Android MBTile reader first implementation

### PR DESCRIPTION
**Pull request by jmcazaux**
Steve, 
here is a functional implementation of the MBTile reader.
I struggled with the test app (UI seems beyond my understanding, but this is not the point) but it worked.
You will need to copy the geography-class.mbtiles from the resources directory to the assets/mbtiles directory of the AutoTester project (I excluded it in the .gitignore, it is not worth checking in twice).

2 caveats though:
- I pass a File object to the reader, not a String (asset name). Dealing with an asset name in the reader would require accessing a Context object. Nothing impossible, but not necessarily a big advantage and there are some risks. Using a file leaves more flexibility to the user and marks responsibilities more clearly.

- This works for bitmap MBTiles and it can probably be used as a base for a vector reader, but definitely cannot be used as is for vectors.

Please tell me what you think about it.

JM

### CODE REVIEW

**Comment by jmnavarro** [comment]
Cool!

One silly question: is it possible to use an stream instead of File as input parameter? That way it would be possible to use a file, memory or network stream (more flexible)

(other) JM

**Comment by jmcazaux** [comment]
Hi JM,
no unfortunately I have not found a standard way neither for opening a
SQLIte DB from a stream nor for getting a File from the asset input stream.

There is lib on github (lost the link right now) that can open SQLite DBs
from Android assets, but it was looking quite specific. In the case of the
SDK, I am not sure the use case is so big (I would guess most apps will
ship DBs separately via download or something).

That can be done, but I thought that using a File was both the most
standard and most flexible option.

Hope this helps,
JM

**Comment by jmnavarro** [comment]
That's too bad!

Anyway, you're right: File is flexible enough. If someone has a network or memory stream, it can always be cached to a tmp file.

Great contribution!

**Comment by jmcazaux** [comment]
Thank JM ;)

**Comment by mousebird** [comment]
Ah right, the bundle issue.  On iOS the OS is doing the unzipping and copying for us, and then presumably deleting the original bundle.  On Android we basically end up doing it ourselves.

It's not ideal, but it's what we have (should be Android's motto).  I think it's a bit easier to put files in place on Android in any case so this is the best approach.  Thanks @jmcazaux!

So @jmnavarro on the subject of the AutoTester.  I think we need to flip the default functionality.  Right now I use a couple setting changes to run each test individually since the AutoTester is nominally for fully automated testing.  We should flip that so that it does individual selected testing by default and we have to explicitly turn on the full auto mode.  The AutoTester has become incredibly useful on both platforms for developing new functionality, so we should roll with that.

**Comment by jmcazaux** [comment]
@mousebird you're welcome!

**Comment by jmnavarro** [comment]
@mousebird I'll do that as soon as I finish my current tasks

**Pull request merged**
