### PR TITLE
Topic/simple style

### PR DESCRIPTION
**Pull request by TimSylvester-mousebird**

### CODE REVIEW

**Review by mousebird — COMMENTED** [review]
Looks good except for the splitVectors issue in Java that I mentioned.

**Review by mousebird — APPROVED** [review]
Thanks for addressing the split issue.

**Comment by TimSylvester-mousebird** [comment]
This last change should help deal with the different ways that Android and iOS handle resources.  I'm assuming we want to be able to use the same stylesheet with, e.g., "bar" in it, and not have to worry about what directory they're in, etc..

**Comment by mousebird** [comment]
Sounds good.  I'll let you merge the branch.

**Pull request merged**
