### PR TITLE
Added synchronized call to LoadedImageWithNSDataAsPNGorJPG

### PR DESCRIPTION
**Pull request by gyrocade**
This seems to fix an issue I was getting with a double free of memory, due to the asynchronous calls to populate the tile data.

### CODE REVIEW

**Comment by mousebird** [comment]
What this effectively does is serialize all the image tile decodes everywhere.  That seems.... bad.

What was the crash you were getting?

**Comment by gyrocade** [comment]
It’s an EXC_BAD_ACCESS.  The latest was in mergeTile inside of MaplyQuadImageTilesLayer.  I’ve also gotten several crashes inside of LoadedImageWithNSDataasPNGorJPG.  There, it reports “double free”.

**Comment by mousebird** [comment]
Is this on ios9 or are you using PKM images?

**Comment by gyrocade** [comment]
iOS 9 primarily, but I've seen it on 8 as well.

**Comment by mousebird** [comment]
Are these PNGs or JPEGs?
And is it possible the same NSData is getting handed into for multiple tiles?

**Comment by gyrocade** [comment]
I believe they are pngs.  Can you do a quick phone call?

**Comment by mousebird** [comment]
Sure, just hit me up by email and we'll set something up.

**Pull request closed without merging**
