### PR TITLE
add removeShadeProgram: method to MaplyBaseViewController

### PR DESCRIPTION
**Pull request by JesseCrocker**

### CODE REVIEW

**Comment by mousebird** [comment]
The underlying GL program needs to be cleaned up too.  On the main thread, no doubt.
I'll put it in as a feature request.

**Comment by JesseCrocker** [comment]
I thought like `Scene void Scene::removeProgram(SimpleIdentity progId)` was already doing all the necessary cleanup, there just wasn't a public interface to it. But on closer inspection it looks like OpenGLES2Program::cleanUp() never gets called.

Can i just add `_program->cleanUp();` to `MaplyShader dealloc` ?

**Comment by mousebird** [comment]
I think it's more complex.  I'll need to make a message and pass it through to the main thread to make sure no one's using it while it's being removed.

It won't cause your app any trouble.  Just check to see if it's there before you create it.  It's not very big.

**Comment by mousebird** [comment]
I can't merge this one is as is.  The underlying program needs to be cleaned out, which is complicated.
I will, however, add an Issue.

**Pull request closed without merging**
