### PR TITLE
Bugfix/881 npe when shutting down map

### PR DESCRIPTION
**Pull request by jmcazaux**
This is a small fix for issue #881

### CODE REVIEW

**Comment by jmnavarro** [comment]
We've just made a big reorg in the repo. Do you mind to close this and resend to `develop` branch?

The file affected is located here: https://github.com/mousebird/WhirlyGlobe/blob/develop/android/library/Android/src/com/mousebird/maply/QuadPagingLayer.java

Thanks!

**Comment by jmcazaux** [comment]
Hi @jmnavarro,

Yes absolutely no worries.

More strategically does it mean that I shall switch to develop as well ?
I am currently tracking and building (Android) from develop_3_0.

**Comment by jmnavarro** [comment]
Yes, probably it's the right time to jump into `develop`. We'll use git-flow branches starting from there.
Anyway, let's listen what @mousebird wants to say

**Comment by mousebird** [comment]
Yup, develop is stable enough now with the code reorganization.
Thanks for bearing with us!

**Pull request closed without merging**
