### PR TITLE
Use Cohen–Sutherland algorithm in ClipLoopToMbr when clipping a line

### LINKED ISSUE #559: Clipping a MaplyVectorLinear where the first and last points are coincident drops the last point
Im calling `[MaplyVectorLinear clipToMbr:upperRight]` on a Linear where the first and last points are coincident and is fully within the clipping MBR, and the returned Linear has the last point dropped. The problem seems to be in `GridClipper ClipLoopToMbr`.

@mousebird Im planning on trying to fix this in the next few weeks, but if you know of a fix for this, let me know.

### PR DESCRIPTION
**Pull request by JesseCrocker**
Clipping open paths in clipper has several bugs, and sometimes crashes, and it doesn't seem like it will ever get fixed. As an alternative I've added an implementation of the Cohen–Sutherland line clipping algorithm, but it is only used when clipping an open path, not a closed path.

Fixes #559

### CODE REVIEW

**Comment by JesseCrocker** [comment]
@mousebird any comment on this?
Im guessing licensing may be the issue? If so i can write a new implementation of the same thing.

**Comment by mousebird** [comment]
@JesseCrocker I just hadn't gotten to it.

Are there licensing issues?  With wikipedia?

**Comment by JesseCrocker** [comment]
I used some code from a wikipedia, i dont totally understand the licensing implications of that. I think it's ok because i put a link with the code?

**Comment by mousebird** [comment]
I don't see any problem with that, but I'd just as soon it was marked, so if there was a problem I could sort it out quickly.  So the link is good, thanks.

**Pull request merged**
