### PR TITLE
More Better way to take snapshot of a view

### PR DESCRIPTION
**Pull request by NSAryan12**
This code caches the texture using the core video methods which is more efficient.

### CODE REVIEW

**Comment by mousebird** [comment]
Yup, that's definitely going to be faster.
I'm curious why you needed a faster snapshot.  Are you taking a lot of snapshots?
What's your app?

**Comment by NSAryan12** [comment]
@mousebird i have a 3D Modelling app on the app store in which you can take screenshot of the model I was using snapshot method of GLKView but it was slow so i decided to create my own snapshot method as i was looking through your code i saw the snapshot method was slow so I decided to contribute😀

**Comment by NSAryan12** [comment]
@mousebird is this good enough to be in the main repo?? 😀

**Comment by mousebird** [comment]
I'm on vacation right now so I won't have a chance to look at this for at least another week.  Thank you for the work, however.

**Comment by NSAryan12** [comment]
Are You back ??

**Comment by NSAryan12** [comment]
?? @mousebird

**Comment by mousebird** [comment]
I appreciate your contribution.  We're getting ready for the next big release and I'm reluctant to make changes like this before that release.  We'll take another look after the release.

**Comment by mousebird** [comment]
I really appreciate your effort here, but I'm not going to merge this in.

First, it's not needed by any current users.  If we were taking a movie, this would be extremely helpful, but it would need to be slightly different.

Second, it's a lot of setup and teardown for functionality that's provided in a standard OpenGL way.  It adds a lot of complexity.

If a user complains about the speed of snapshots, then we'll revisit your contribution.

**Pull request closed without merging**
