### PR TITLE
Updated latest deltaT values

### PR DESCRIPTION
**Pull request by niskov**
Updated all values until June 1st 2017 (values taken from http://maia.usno.navy.mil/ser7/deltat.data)

### CODE REVIEW

**Comment by mousebird** [comment]
Cool.  Happy to merge it in.  What are you doing that you need these updated?

**Comment by niskov** [comment]
I'm developing information kiosks to synagogues. They rely heavily on
different sun and moon events, hence the need for accuracy

**Comment by saildronesteve** [comment]
Oooo, neat.  Is there a web page anywhere?  I'm curious to know more.

**Comment by niskov** [comment]
Sure, hope your Hebrew is strong :)
www.binalaitim.co.il

**Pull request merged**
